-- Run this once in the Supabase SQL editor.
create table if not exists public.password_reset_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists password_reset_tokens_user_id_idx
    on public.password_reset_tokens(user_id);
create index if not exists password_reset_tokens_expires_at_idx
    on public.password_reset_tokens(expires_at);

alter table public.password_reset_tokens enable row level security;
